apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhook-server-certificate
  namespace: {{ namespace }}
spec:
  secretName: webhook-server-tls
  issuerRef:
    kind: ClusterIssuer
    name: lets-encrypt
  dnsNames:
    - {{ hostname }}