apiVersion: v1
kind: Service
metadata:
  name: webhook-server-service
  namespace: {{ namespace }}
spec:
  selector:
    app: webhook-server
    branch: {{ git_branch }}
  ports:
    - name: javalin-port
      port: 8080