- debug:
    msg: Building Docker image app={{ app }} publish={{ publish }}

- name: Setup output directory
  block:
    - name: Delete existing output directory
      file:
        path: output
        state: absent

    - name: Create main output directory
      file:
        path: output
        state: directory

- name: Gather git information
  import_tasks: tasks/git-info.yml

- name: Install dependencies
  import_tasks: tasks/install-dependencies.yml

- name: Clean and build gradle project
  shell: cd ../ && ./gradlew clean assemble && ./gradlew :{{ app }}:distTar

- name: Generate the Dockerfile
  template:
    src: docker/{{ dockerfile }}
    dest: output/Dockerfile-{{ app }}
  vars:
    build_timestamp: "{{ ansible_date_time.iso8601 }}"

- name: Build Docker image
  when: not publish
  shell: |
    docker build \
      -t ghcr.io/ruchira088/webhook-server-{{ app }}:{{ git_branch }} \
      -t ghcr.io/ruchira088/webhook-server-{{ app }}:{{ git_branch }}-{{ git_commit }} \
      -f output/Dockerfile-{{ app }} \
      ../{{ app }}/build/distributions/

- name: Build and publish Docker image to GitHub container registry
  when: publish
  block:
    - name: Login to GitHub container registry
      command: docker login ghcr.io -u USERNAME -p {{ access_token }}
      vars:
        access_token: "{{ lookup('aws_ssm', '/github/packages/read-write-token', region='ap-southeast-2') }}"

    - name: Build and publish Docker image
      shell: |
        docker buildx build \
          --push \
          --platform linux/arm64,linux/amd64 \
          -t ghcr.io/ruchira088/webhook-server-{{ app }}:{{ git_branch }} \
          -t ghcr.io/ruchira088/webhook-server-{{ app }}:{{ git_branch }}-{{ git_commit }} \
          -f output/Dockerfile-{{ app }} \
          ../{{ app }}/build/distributions/

- name: Cleanup output directory
  file:
    path: output
    state: absent

- debug:
    msg: Completed Docker image built app={{ app }}