FROM eclipse-temurin:21-jre

LABEL org.opencontainers.image.source=https://github.com/ruchira088/webhook-server

ENV GIT_BRANCH {{ git_branch }}
ENV GIT_COMMIT {{ git_commit }}
ENV BUILD_TIMESTAMP {{ build_timestamp }}

WORKDIR /opt/webhook-server-{{ app }}

ADD {{ app }}.tar .

CMD [ "/opt/webhook-server-{{ app }}/{{ app }}/bin/{{ app }}" ]
